### ISSUE TITLE
board not loading in Safari private browsing (incognito window)

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1009]
It is due to `localStorage` that is blocked in private browsing

Related to #973

**Comment by lmarikannan** [comment]
Fixed in this commit d9fe36a

**Comment by rrjanbiah** [comment]
localForage doesn't fix this issue. Refer https://github.com/localForage/localForage/issues/145

**Comment by lmarikannan** [comment]
Fixed on this commit 7a8828c
