### ISSUE TITLE
[Activities logging bug] Too many activities crash GUI

### ISSUE THREAD

**Issue by theriverman** [RestyaPlatform/board#1119]
Hi,

I made lots of actions in a board within about 25 minutes (created lots of cards and lists and all). 
Logging in as ADMIN I get blank admin page (the system cannot load the recent user activities) and I'm struggling to switch between admin pages (i gotta right click and open on new tab).

I tried turning off "All activities" function, but it is hard-coded for Admin user.

See photos below:

![screen shot 2017-03-15 at 15 27 49](https://cloud.githubusercontent.com/assets/22156894/23953312/84ecf8e6-0994-11e7-97ad-f57fb6356c8f.png)
![screen shot 2017-03-15 at 15 28 08](https://cloud.githubusercontent.com/assets/22156894/23953313/850aada0-0994-11e7-96a8-53267df5cfd4.png)

If you need further informations or have any idea/workaround to solve the issue, please let me know!

/riverman

**Comment by baskar383** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/1116. we are already got  based on your issue  currently we are  working on this issue once fixed we will update you.

**Comment by lmarikannan** [comment]
@theriverman  Sorry for the trouble. Actually this error occur due to refresh token and access token expiration time. Now we have fixed this on 2 files.

Need to replace the r.php file on `/server/php/R/r.php` path with this file [r.txt](https://github.com/RestyaPlatform/board/files/849781/r.txt) and change the file format `.txt` to `.php`.

And also replace the bootstrap.php file on `/server/php/boostrap.php` path with thie file [bootstrap.txt](https://github.com/RestyaPlatform/board/files/849786/bootstrap.txt) and change the file format  `.txt` to `.php`. It'll works.

**Comment by theriverman** [comment]
Hi,

The problem still persists [or did I miss something?].

I did change both files to the new ones you linked above.
I did restart nginx and cleared the complete history/cookies/cache of Internet Explorer, but still facing the issue --> The `http://192.168.1.100/#/activities` site is blank, not loading the logs.
If I click _Users/Boards/Roles/Apps/etc_... then It does nothing. _If I reload the site_, it's back again.

**Extra info**: If I shrink the page width to trigger the mobile-friendly mode, then on the bottom it says "Syncing" when I move the cursor above the Restyaboard Logo.
If clicking "Load more activities" it gets stuck and loads forever.

/riverman

**Comment by lmarikannan** [comment]
@theriverman Can you please open your browser console and see if there's any errors, and also look up `/api/v1/activities.json` API endpoint call response, and paste that response here.

**Comment by theriverman** [comment]
Hi,

I tried accessing that file, but I could not download it through the browser [download failed].
However, I did some research, and I found that my crontabs were failing to run.

I re-created them with `sudo crontab -e` and I guess that the `card_due_notification.sh` and `webhook.sh` scripts are in connection with this issue.

I executed them and my activities loaded in the Admin panel.

If you can confirm it, then the ticket can be closed!

Thanks,
riverman

**Comment by lmarikannan** [comment]
@theriverman Here we attached a [video link](https://drive.google.com/open?id=0B1bpPqx9YfPJaVMzcmpBTnFlLWc) to get the response from activities API endpoint. Please follow that video procedures and copy the response data from your server, and paste it here.

**Comment by theriverman** [comment]
Hello, I'm not able to check this now, maybe early next week.
I close this issue now and will open+comment again later.
