### ISSUE TITLE
Install script is failing with PostgreSQL installation

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1226]
Looks like for many users, install script is failing at PostgreSQL installation. 

*Internal note*:  Prem seems to be uninstalling PostgreSQL and rerunning the script (Not sure, if that's a correct approach)

**Comment by lmarikannan** [comment]
Fixed on this commit - c0d4d34

**Comment by rrjanbiah** [comment]
How this will fix the issue?

**Comment by lmarikannan** [comment]
This issue fixed by this change - https://github.com/RestyaPlatform/board/commit/c0d4d3452217020d5685445637b207fe873bcfd5#diff-e2930341cebfe21b6b1fd322a42667e2R1010.

**Comment by rrjanbiah** [comment]
Document the changes. It is still not clear what this commit is "fixing" and how

**Comment by lmarikannan** [comment]
Fixed on this commit b393688. There are two postgresql queries on single line on 496th line and 994th line. And drop database query is returning error, so the installation stopped with `PostgreSQL database creation failed with error code 36`. Now drop database query is removed from that two lines.
