### ISSUE TITLE
Issues with board visibility (Private/Public/Organization)

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#129]
From https://groups.google.com/forum/#!topic/restya/Fj5RvUjlV_8

I've been having some issues with board visibility.

To sum it up, my biggest problem is this: members of an organization cannot view the contents of a board that belongs to that organization if they have not been added to the board. Is this working as intended?

I'll give an example, just in case I wasn't clear enough: I create an organization, and add all my colleagues there. Then I create a board and set it's visibility to "Organization". The description indicates that all members of the organization can view the board, but only members can edit, which is fine. If a colleague of mine who belongs to the organization access the organization menu, they can see the board. It's there. However, when the click the board to view it's contents, a message says that he cannot do that, because the board may be private. Of course, the board is not private.

To put in terms of an use case: I'd like for people in my organization to be able to view (but not necessarily edit) the boards made by other people in the organization. However, I don't want to have to manually assign everyone to every board, as that is extremely time consuming, and very error-prone. I'd prefer if public boards would just show up to everyone, or if organization boards could be actually seem by everyone in a organization. Is there any solution to my issue?

**Comment by rrjanbiah** [comment]
@srileka Kindly check

**Comment by sathya313** [comment]
Yes, this issue is reproducible.

**Comment by rrjanbiah** [comment]
@sathya313 Thanks for checking

**Comment by rrjanbiah** [comment]
We have planned to do it like this:

*  If the visibility is "Organization", we'll add all members of the organization to the board
*  If further members (from other organization) are added, the visibility level will reset to "Private" with warning.

**Comment by rrjanbiah** [comment]
Further feedback from Fernando Barbosa through forum:

That seems fine. However, how would I have a "read-only" user in an organization board? Let's assume that I have someone from outside the organization, and I want that person to be able to see the board, but not to edit it in any way. What would be the correct approach? Should this person be given a Guest account (which should not be able to edit anything), and then have the Guest be added to the organization?

As a matter of fact, what do you think about this approach:

* If the visibility is "organization", all members of the organization can view the board, but not edit it.
* Only members of the organization can be added to an organization board (if a member is kicked out of an organization, he is automatically kicked out of any boards belonging to that organization)
* When an organization member is added to an organization board, he can edit it.
* That'd probably require a whole new feature, but ideally organization members could request the board owner to be added to a board.

This way:

* If you want to give "read-only" access to someone, just add that person to the organization, but do not add the account to any board.
* You can still control who can edit a board within an organization. That can be desirable if, for example, you have an organization representing a company with hundreds of people. Although it makes sense that everyone can see all boards (unless the board is set to private -- but that's a non-issue, because if the board is set to private it is not set to organization), maybe not everyone should be able to edit all boards (e.g. people would only edit the task boards related to the area of the company or to the projects they work at).
* You do not have the issue of adding people from outside of the organization at all. In the scenario you've described, changing the board to Private could cause some confusion among members, as it'd not show up in the Organization view anymore.
What do you think about it?

As long you're able to have "read-only" accounts in Organization boards, either way is fine for me, but I personally prefer the second option (though I might have missed some reason that would make the first option more desirable).

**Comment by rrjanbiah** [comment]
As a quick and temporary fix to the situation, we have pushed https://github.com/RestyaPlatform/board/commit/5d55730e83a704b2a2f669ca81a0719fff32397c

* If the visibility is "Organization", we're adding all the members of the organization to the board
* If any members are added to particular organization, we're adding those new members to the all the boards of the organization.

Note: We're still working to resolve it in better approach. So, keeping this as open.

**Comment by ssivachidambaram** [comment]
Done.

**Comment by thesourcer** [comment]
I just downloaded and installed restyaboard today (using the linux install script), but I am still having this same issue.  Is this issue not solved in the version that is installed by the shell installation script?  If not, is there another possibility as to why I am getting the same problem (organization members unable to view organization scope boards)?

**Comment by rrjanbiah** [comment]
@thesourcer Our latest fixes are available in `dev` branch alone. We've planned to release it tomorrow and then it will be available in `master` too.
