### ISSUE TITLE
wrong timezone in the iCal file

### ISSUE THREAD

**Issue by fswmlu** [RestyaPlatform/board#1325]
iCal file will be created with UTC timezone, even though on server it is correctly changed to UTC+2 (Europe/Vienna)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/d1cc6530f6548ad8f9db0788100f64ec4bfdca1f

**Comment by fswmlu** [comment]
@lmarikannan: I'm afraid, the timezone is still wrong :-(
this event: DTSTART;TZID=Europe/Vienna:20171227T130000Z shows like 1.00 PM in restyaboard calendar, but 2.00 PM in outlook. Mayby the problem is... the "Z" on end of the time string, because:
DTSTART:20171227T130000   ;Local time
DTSTART:20171227T130000Z ;UTC time

**Comment by ssivachidambaram** [comment]
@fswmlu Due to this `TZID=Europe/Vienna` in ics file, time will convert based on the timezone set in the application like Google Calendar & Outlook automatically. Can you please send your ICS file and timezone of Outlook?

**Comment by fswmlu** [comment]
@ssivachidambaram Please find enclosed the requested information. Please note, the timezone in Europe is variable, CET = UTC+1 and CEST = UTC+2 (https://www.timeanddate.com/time/zone/austria).
I tamporary changed the the line 51+52 in the file ical.php. It helps, but propably until the change to the summer time...
![2017-12-29_075622](https://user-images.githubusercontent.com/31476853/34431401-2a58f0e2-ec6f-11e7-9f1f-052d576bd0cf.png)
![2017-12-29_074217](https://user-images.githubusercontent.com/31476853/34431403-2c9d4c5e-ec6f-11e7-9f9c-b68fb65987c3.png)
![2017-12-29_073816](https://user-images.githubusercontent.com/31476853/34431406-2f378a88-ec6f-11e7-9d67-292afbf63c82.png)
![2017-12-29_073501](https://user-images.githubusercontent.com/31476853/34431410-3823f91a-ec6f-11e7-98ad-e81cbc4de12a.png)
[ical.zip](https://github.com/RestyaPlatform/board/files/1592698/ical.zip)

**Comment by ssivachidambaram** [comment]
@fswmlu We are checking this issue and will update you.
