### ISSUE TITLE
Doesn't import all comments from Trello JSON - only 10-20 comments per card can import

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1408]
I am using the newest version of Restyaboard. 
Just after install had the known problem with php-fpm which I have solved, and now I can import from Trello.
I have bought Trello Business so I can export full JSON files.

With those files, when importing my JSON, for some reason, only some of my comments get imported (about 10-20 per card). That happens on cards where i have about 200-300 comments. Also, the dates and order are all mixed up.
When i search inside the JSON, all of the comments are available.

**Comment by rrjanbiah** [comment]
@darko190 Are these data highly confidential? If not, is it possible for you to share the file to our email address or have our team look at the issue at least remotely?

**Comment by darko190** [comment]
@rrjanbiah I will find a board with smaller confidentiality risk, and I will share one of the JSON's with you in a moment.

**Comment by darko190** [comment]
@rrjanbiah here you go
[TEST.txt](https://github.com/RestyaPlatform/board/files/1531281/TEST.txt)

**Comment by dadarko** [comment]
Would you give me Your e-mail adress?

**Comment by dadarko** [comment]
I have tried importing my JSON to the official demo app, and it still doesn't work..... Only 10-20 comments per card... 
http://board.demo.restya.com/#/board/8
Sticking with Trello unfortunately.... Restya obviously isn't ready for our migration yet...

**Comment by dadarko** [comment]
Can you please promote this to a Bug?

**Comment by ssivachidambaram** [comment]
> Would you give me Your e-mail adress?

@dadarko Can you please send json file to this email address `info@restya.com`?

**Comment by dadarko** [comment]
I have sent you the data.

**Comment by ssivachidambaram** [comment]
@dadarko Yes. We are working on the issue. Will update you once its fixed.

**Comment by sridhar391** [comment]
@dadarko Now when importing  comments from Trello JSON all comments will be imported and this has been fixed in #1417

**Comment by dadarko** [comment]
I Tried adding the code, and it is still the same. I also tried importing on your demo server. Still not working...

**Comment by dadarko** [comment]
This needs to be reopened, the fix doesn't work.

**Comment by ssivachidambaram** [comment]
@dadarko Currently its fixed in development server. Here you can check the demo of your Trello project http://boarddev.demo.restya.com/#/board/9/card/696 - admin // restya.
