### ISSUE TITLE
Child card updation, start date and due date updation is wrong 

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2941]
## Expected Behavior

Child card updation, start date and due date updation is wrong 

## Current Behavior

Child card updation, start date and due date updation is wrong 

## Screenshots (if appropriate):

![due_date_child](https://user-images.githubusercontent.com/14290356/63945338-c45c5e80-ca90-11e9-81af-50df02cefb04.png)

## Steps to Reproduce (for bugs)

1. At the time we add the two child card, start date and due date is wrong.
2. First card(Test a) set the "start date and due date".
3. Second card(Test b) set the "due date" only.
4. Then open the third card and First add the "Test b" card and then add the "Test a" card.
5. At the time, date is wrong

**Comment by sridhar391** [comment]
@srileka We have fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not Fixed.

If we set the due date "Aug 1".

Refer the screenshot

![Due_date](https://user-images.githubusercontent.com/14290356/68027836-6be84e00-fcd9-11e9-83c0-b6816de1ba54.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not Fixed.

After added the card dependency -> in child card, remove the start date and change the due date (child due date is greater than the parent start date). That time date is wrong

![date_wrong](https://user-images.githubusercontent.com/14290356/68303850-ae8b9b00-00ca-11ea-876f-d0e6bc96fc86.png)

**Comment by sridhar391** [comment]
Related https://github.com/RestyaPlatform/board/issues/3322

**Comment by sridhar391** [comment]
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8(Roxette)

**Comment by srileka** [comment]
Issue not Fixed.

Case 1: If card dependency -> child card having only due date, that time start date and due date date is wrong.

Case 2: 
1. At the time we add the two child card, start date and due date is wrong.
2. First card(Test a) set the "start date and due date".
3. Second card(Test b) set the "due date" only.
4. Then open the third card and First add the "Test b" card and then add the "Test a" card.
5. At the time, date is wrong

Case 3: After added the card dependency -> in child card, remove the start date and change the due date, that time card dependency alert message is not displayed

**Comment by srileka** [comment]
Issue Not Fixed

Case 1:

Parent card having the "start date and due date". 

Then add the child card (child cards are not having the start date and due date".

Then set the "due date" in child card . 

Then change the "due date" in parent card.

After change the date in parent card, child cards due dates are wrong 

![child_reopen_1](https://user-images.githubusercontent.com/14290356/69812021-66691f80-1215-11ea-9375-b20cca1144eb.png)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
