### ISSUE TITLE
In Copied list, card  position is not updated correctly in other user browser

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3019]
## Expected Behavior

In Copied list, card  position is not updated correctly in other user browser

## Current Behavior

In Copied list, card  position is not updated correctly in other user browser

## Screenshots (if appropriate):

![card position](https://user-images.githubusercontent.com/14290356/64170457-cb5ae680-ce6d-11e9-8d8f-a6952e4474a3.png)

**Comment by sridhar391** [comment]
@srileka We have fixed the above issue in the dev branch and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not fixed.

In Copied list, card position is not updated correctly in other user browser.

Both user default sorting displayed ascending. "Default sort for cards = position : asc"

**Comment by sridhar391** [comment]
@srileka Currently, not able to reproduce the issue, please feel free t reopen the issue if occurred again

**Comment by sridhar391** [comment]
Fixed the above issue in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
