### ISSUE TITLE
In Instant add card, label box design gets broken

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3132]
## Expected Behavior

In Instant add card, label box design gets broken

## Current Behavior

In Instant add card, label box design gets broken

## Screenshots (if appropriate):

![instant_label_design](https://user-images.githubusercontent.com/14290356/64953829-88533700-d8a1-11e9-8951-88d9981859b0.png)

**Comment by sridhar391** [comment]
Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not fixed.

![2019-11-15_16-13-31](https://user-images.githubusercontent.com/14290356/68937019-a82faa00-07c1-11ea-9ae7-28156d91c4f8.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.8(Roxette)

**Comment by srileka** [comment]
Issue Not Fixed.

If we add the more labels, label design gets broken.

![label_design_reopened](https://user-images.githubusercontent.com/14290356/69787539-c7c3cb00-11e2-11ea-995d-d23a34512497.png)

**Comment by sridhar391** [comment]
The Label form is shown within the instant add card form and you can maximize the Instant add card form to add more labels without hide
