### ISSUE TITLE
While clicking the template in the add card settings dropdown menu, loading not shown until card template is shown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3369]
## Expected Behavior
While clicking the template in the add card settings dropdown menu, loading should be shown until card template is shown

## Current Behavior
While clicking the template in the add card settings dropdown menu, loading not shown until card template is shown

**Comment by sridhar391** [comment]
Fixed the above issue in the Card Template app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not Fixed.

Now, card create template option is not displayed in model card. But admin side template option is enabled.

![2019-11-15_12-52-31](https://user-images.githubusercontent.com/14290356/68923924-87595b80-07a5-11ea-89d2-fe1f5d3ba62c.png)

**Comment by sridhar391** [comment]
@srileka Please check if you have the permission to create template from card
