### ISSUE TITLE
If we open the board or go to the boards page, white background has been displayed until board open

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3428]
## Expected Behavior
If we open the board or go to the boards page, white background should not be displayed until board open

## Current Behavior
If we open the board or go to the boards page, white background has been displayed until board open

## Screenshots (if appropriate):
![background](https://user-images.githubusercontent.com/17172525/68990469-6c581b80-0879-11ea-949b-e070c3aec8a0.png)

**Comment by srileka** [comment]
Issue not Fixed.

If we open the board, white background has been displayed until board open.

**Comment by baskar383** [comment]
Fixed the issue in the commit bf82efe171d92deb88fe582123f0b10de491987e and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issue not fixed
Case: If we open the board, white background has been displayed until board open.

**Comment by sridhar391** [comment]
We are loading the image while opening the board, but it takes time to load the image in the broweser
