### ISSUE TITLE
If we edit the label and then go to the some other views and then come grid view, edited labels are did not updated properly

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3570]
## Expected Behavior
If we edit the label and then go to the some other views and then come grid view, edited labels are did not updated properly

## Current Behavior
If we edit the label and then go to the some other views and then come grid view, edited labels are did not updated properly

## Screenshots (if appropriate):
![35_label_edit](https://user-images.githubusercontent.com/17172525/69844173-00ba7900-1291-11ea-8a05-d1eda4cb8fb2.png)

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to reproduce the issue

**Comment by sridhar391** [comment]
Issues Not Fixed
Case: Remove the old label and then add the new label, then go to some other views and then come grid view, edited labels are did not updated properly

**Comment by sridhar391** [comment]
Fixed the above issue in the `dev` branch and the fix will be available in the upcoming release v0.6.9 (Stereopony)

**Comment by srileka** [comment]
Issue not Fixed.

Case 1: Remove the old label, then go to some other views and then come grid view, edited labels are did not updated properly

Case 2: Remove the old label and then add the new label, then go to some other views and then come grid view, edited labels are did not updated properly
