### ISSUE TITLE
After removed the board member, member did not remove from the card

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3607]
## Expected Behavior
After removed the board member, member did not remove from the card

## Current Behavior
After removed the board member, member did not remove from the card

## Screenshots (if appropriate):
![12_remove_member](https://user-images.githubusercontent.com/17172525/69898529-e364d800-1380-11ea-8282-0aced5172727.png)

**Comment by sridhar391** [comment]
Issue not fixed
Case: While removing the member from the board, other user browser did not open the board. After removed from the board, other user able to open and close the board. After refreshing the page only, boards removed

**Comment by sridhar391** [comment]
Issue Not fixed
Case: While removing the member from the board, other user browser did not open the board. After removed from the board, other user able to open and close the board. After refreshing the page only, boards removed

**Comment by sridhar391** [comment]
Fixed the above issue in `dev` branch and the fix will be available in the upcoming release v0.6.9 (Stereopony)

**Comment by srileka** [comment]
Issue Not Fixed.

After removed the board member, member did not remove from the old card. Please check the current user and other user browser

![reopen_3607](https://user-images.githubusercontent.com/14290356/73823596-9f79cd80-481e-11ea-9706-0602bbf0f79b.png)

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to re-produce the issue, please feel free t reopen if the issue occurred again and please also provide steps
