### ISSUE TITLE
Sorting icon did not working properly in attachments

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3611]
## Expected Behavior
Sorting icon did not working properly in attachments

## Current Behavior
If we click the sorting icon again and again, same sorting icon only displayed. Icon does not change. And if we click the left side of the attachments, sorting icon has been removed

## Screenshots (if appropriate):
![16_attachments_sort_icon](https://user-images.githubusercontent.com/17172525/69898614-caa8f200-1381-11ea-9da4-78cf22d81c4a.png)

**Comment by sridhar391** [comment]
Issue Not Fixed

If we click the sorting icon again and again, same sorting icon only displayed. Icon does not change. And if we click the left side of the attachments, sorting icon has been removed

**Comment by sridhar391** [comment]
Fixed

**Comment by srileka** [comment]
Issue Not Fixed.

If we click the left side of the attachments, sorting icon has been removed

![reopen_3611](https://user-images.githubusercontent.com/14290356/73823912-41011f00-481f-11ea-9394-0bba2e00d111.png)
