### ISSUE TITLE
Empty page after timeout

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#4010]
From https://groups.google.com/d/msg/restya/bTeXZLO2jY4/Ih80SPcTAwAJ (Samuel Arcos):

so, after i leave a board opened for a while, i think google chrome tries to refresh the page, but nothing comes up, 
i go in there and see a blank page with the restya logo on the top left, the hr, (grey line under the logo) and then a box, looks like a message box, empty, nothing in it. (see attached image)

then I try to go to the root of the domain, https://board.domain.com 
nothing comes up, blank page 

I then delete the browser cookies

then I refresh 
then the login page comes up, and everything works again.

any ideas on how to make this stop,
I am thinking that my session is expiring,  but how do I make it so it will take me to the login page instead of the blank page.

## Screenshots:

![Capture](https://user-images.githubusercontent.com/4907427/77636160-ac42b400-6f79-11ea-9054-49df6022dcd3.jpeg)

**Comment by morbificagent** [comment]
Same here :-(
Dont know what to do

**Comment by sridhar391** [comment]
Can you please tell us if your Restyaboard version is v0.6.8 and you can check your Restyaboard version by clicking the user image icon in the footer and click the "About Restyaboard" option like the attached image "about_restyaboard_option.png" and in the About page check the Restyaboard version like the attached image "restyaboard_version.png"

![about_restyaboard_option](https://user-images.githubusercontent.com/17172525/83245820-e79e7080-a1be-11ea-9b1c-4de7dbbe40e5.png)

![restyaboard_version](https://user-images.githubusercontent.com/17172525/83245827-eb31f780-a1be-11ea-8c75-a56c2dca63e1.png)

**Comment by c-nv-s** [comment]
I'm seeing the same behavior with this same version v 0.6.8 (2019-12-16).

**Comment by sridhar391** [comment]
@c-nv-s We have released the latest Restyaboard version v0.6.9 (Stereopony) and can you please update your Restyaboard using our easy install script "restyaboard.sh" by following the instructions from the link https://restya.com/board/docs/installation-in-ubuntu-using-shell-script/#2

**Comment by c-nv-s** [comment]
> @c-nv-s We have released the latest Restyaboard version v0.6.9 (Stereopony) and can you please update your Restyaboard using our easy install script "restyaboard.sh" by following the instructions from the link https://restya.com/board/docs/installation-in-ubuntu-using-shell-script/#2

still the same behavior with the latest release, the welcome dashboard displays correctly immediately on login ( also displayed the "what's new video", however on return to the dashboard after navigating to another part of the app the dashboard is blank.

**Comment by c-nv-s** [comment]
in case this helps anyone... for those who have quite strict browser privacy settings on, including ad blockers... try adding your restyaboard site as an exception in your browser's "cookies and data" settings, and perhaps as an exception on your ad blocking tool too.
This seems to have helped resolve the blank dashboard on return from navigating briefly away to a different site.
The issue still seems to remain though if you have embeded your restyaboard as an external site or iframe within another web app... i.e. on first login the dashboard and ui are fully functional, however if you briefly navigate away to a different site then on your return you are still logged in however dashboards are blank... ( admin pages are accessible, and you can possibly access a board via a link in the activities history, but no dashboards unless you logout then back in ).

**Comment by sridhar391** [comment]
@c-nv-s Can you please give us more details like OS, Browser, Browser version, RAM, etc.
