### ISSUE TITLE
Divider on card modal is not completely resizeable 

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#993]
Looks like Mac Chrome specific, especially seems to happen only in big monitor

**Comment by xorander00** [comment]
Confirmed.  This is what I was referring to in the other issue.  I can only resize to the left, not right.  Windows/Chrome on a larger monitor (28" @ 2560x1440).

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/f52247ca7a7b5ad73ecabf84205e359dbefd256b

**Comment by rrjanbiah** [comment]
Issue is still reproducible, now having slightly different behavior.

**Comment by baskar383** [comment]
Fixed in this commit 8d2317b
